POST http://localhost:8080/usuarios/post
Accept: application/json
Content-Type: application/json

{
  "username": "cahr"
}

###

POST http://localhost:8080/seguidores/post
Accept: application/json
Content-Type: application/json

{
  "usuarioS": 4,
  "userFollow": 3
}

###


POST http://localhost:8080/twetts/post
Accept: application/json
Content-Type: application/json

{
  "texto": "HomeOffice",
  "idTweet_idUser": 4
}

###

GET http://localhost:8080/timeline/get?usuarioline=1
Accept: application/json
Content-Type: application/json