POST http://localhost:8080/usuarios/post
Accept: application/json
Content-Type: application/json

{
  "username": "Cp"
}

###

POST http://localhost:8080/seguidores/post
Accept: application/json
Content-Type: application/json

{
  "usuarioS": 5,
  "userFollow": 1
}

###


POST http://localhost:8080/twetts/post
Accept: application/json
Content-Type: application/json

{
  "texto": "Hola Mundo!",
  "idTweet_idUser": 5
}


###

GET http://localhost:8080/timeline/2
Accept: application/json
Content-Type: application/json


###

GET http://localhost:8080/cache/entries/timelines/2
Accept: application/json
Content-Type: application/json


###






GET http://localhost:8080/timeline/get?usuarioline=2
Accept: application/json
Content-Type: application/json
